name: flutter_sample_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.0.0-dev.9
  state_notifier: ^0.7.2+1
  json_serializable: ^6.3.1
  freezed_annotation: ^2.1.0

  dio: ^4.0.6
  retrofit: ^3.0.1+1

  get: ^4.6.5

  webview_flutter: ^3.0.4

  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  retrofit_generator: ^4.0.3+1

flutter:

  uses-material-design: true

  assets:
    - .env